export const assetFindingdummy = {
	getAsset: {
		id: "0x58ff",
		findings: [
			{
				id: "0x5cb3",
				name: "offer.breachlock.com_Traceroute for the host",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x597a",
					name: "Traceroute for the host",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.258Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x5cb4",
				name: "offer.breachlock.com_Operating System Fingerprinted",
				vulnerability: {
					cvssScore: 0,
					severity: "LOW",
					id: "0x597b",
					name: "Operating System Fingerprinted abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijk",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.265Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "MEDIUM",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x5cb6",
				name: "offer.breachlock.com_Fully Qualified Domain Name (FQDN) Resolved",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5983",
					name: "Fully Qualified Domain Name (FQDN) Resolved",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.273Z",
				findingType: "N/A",
			},
			{
				id: "0x5cb7",
				name: "offer.breachlock.com_Inconsistent Forward and Reverse DNS Lookup Results",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x597d",
					name: "Inconsistent Forward and Reverse DNS Lookup Results",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.274Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb8",
				name: "offer.breachlock.com_Open Network Ports Found on Server",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5977",
					name: "Open Network Ports Found on Server",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.275Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x7cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "LOW",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5we",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5asas",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "MEDIUM",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x5cb5kkkk",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5---",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0--x5cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x5cb5ppp",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cbasddsds",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5ssjjj",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5sdasasdfc",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb55555",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "New Discovered",
			},
			{
				id: "0xzzz5cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "LOW",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "Rediscovered",
			},
			{
				id: "0xoooo5cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "MEDIUM",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: "Rediscovered",
			},
		],
	},
};

export const ipFindingdummy = {
	getIPAddress: {
		id: "0x58ff",
		findings: [
			{
				id: "0x5cb3",
				name: "offer.breachlock.com_Traceroute for the host",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x597a",
					name: "Traceroute for the host",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.258Z",
				findingType: "Rediscovered",
			},
			{
				id: "0x5cb4",
				name: "offer.breachlock.com_Operating System Fingerprinted",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x597b",
					name: "Operating System Fingerprinted abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijk",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.265Z",
				findingType: "New Discovered",
			},
			{
				id: "0x5cb5",
				name: "offer.breachlock.com_Banner Grabbing Possible",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5973",
					name: "Banner Grabbing Possible",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.266Z",
				findingType: null,
			},
			{
				id: "0x5cb6",
				name: "offer.breachlock.com_Fully Qualified Domain Name (FQDN) Resolved",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5983",
					name: "Fully Qualified Domain Name (FQDN) Resolved",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.273Z",
				findingType: "N/A",
			},
			{
				id: "0x5cb7",
				name: "offer.breachlock.com_Inconsistent Forward and Reverse DNS Lookup Results",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x597d",
					name: "Inconsistent Forward and Reverse DNS Lookup Results",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: false,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.274Z",
				findingType: null,
			},
			{
				id: "0x5cb8",
				name: "offer.breachlock.com_Open Network Ports Found on Server",
				vulnerability: {
					cvssScore: 0,
					severity: "INFORMATIONAL",
					id: "0x5977",
					name: "Open Network Ports Found on Server",
				},
				wfName: "ngsam-nw-0-0-1-cggh8ukq",
				isAutoAdded: true,
				isFalsePositive: true,
				isManual: false,
				isPatched: false,
				updatedAt: "2023-12-23T07:04:10.275Z",
				findingType: null,
			},
		],
	},
};

export const assetAssetGroupdummy = {
	getAssetGroup: {
		id: "0x57e93",
		assets: [
			{
				findings: [
					{
						id: "0x2f4a",
						name: "offer.breachlock.com_Filtered/Closed Network Ports Found on Server",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2729",
							name: "Filtered/Closed Network Ports Found on Server",
						},
						wfName: "ngsam-nw-0-0-1-kpgthok1",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:19:15.661Z",
						findingType: "New Discovered",
					},
					{
						id: "0x2f4b",
						name: "offer.breachlock.com_Inconsistent Forward and Reverse DNS Lookup Results",
						vulnerability: {
							cvssScore: 4.8,
							severity: "MEDIUM",
							id: "0x271d",
							name: "Inconsistent Forward and Reverse DNS Lookup Results",
						},
						wfName: "ngsam-nw-0-0-1-kpgthok1",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:19:15.662Z",
						findingType: "New Discovered",
					},
					{
						id: "0x2f4c",
						name: "offer.breachlock.com_Fully Qualified Domain Name (FQDN) Resolved",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2721",
							name: "Fully Qualified Domain Name (FQDN) Resolved",
						},
						wfName: "ngsam-nw-0-0-1-kpgthok1",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:19:15.66Z",
						findingType: "New Discovered",
					},
				],
			},
			{
				findings: [
					{
						id: "0x2f4a",
						name: "app.breachlock.com_Fully Qualified Domain Name (FQDN) Resolved",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2721",
							name: "Fully Qualified Domain Name (FQDN) Resolved",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.884Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2eec",
						name: "app.breachlock.com_Open Network Ports Found on Server",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2713",
							name: "Open Network Ports Found on Server",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.885Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2eed",
						name: "app.breachlock.com_Traceroute for the host",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x271f",
							name: "Traceroute for the host",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.88Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2eee",
						name: "app.breachlock.com_Server Software Version(s) Disclosed",
						vulnerability: {
							cvssScore: 3.7,
							severity: "LOW",
							id: "0x27d9",
							name: "Server Software Version(s) Disclosed",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.881Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2eef",
						name: "app.breachlock.com_Operating System Fingerprinted",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2720",
							name: "Operating System Fingerprinted",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.882Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2ef0",
						name: "app.breachlock.com_SSL Certificate Information",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x27ee",
							name: "SSL Certificate Information",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.882Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2ef1",
						name: "app.breachlock.com_Banner Grabbing Possible",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2711",
							name: "Banner Grabbing Possible",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.883Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x2ef2",
						name: "app.breachlock.com_Robots.txt File Present",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x2e33",
							name: "Robots.txt File Present",
						},
						wfName: "ngsam-nw-0-0-1-y8gvv8tv",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-06T17:34:28.884Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51cb",
						name: "app.breachlock.com_Server Software Information Disclosed",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x515e",
							name: "Server Software Information Disclosed",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.567Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51cc",
						name: "app.breachlock.com_Web Server Vulnerable to HTTP Host Header Attack",
						vulnerability: {
							cvssScore: 3.1,
							severity: "LOW",
							id: "0x5157",
							name: "Web Server Vulnerable to HTTP Host Header Attack",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.568Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51cd",
						name: "app.breachlock.com_Service Provider",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x5161",
							name: "Service Provider",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.569Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51ce",
						name: "app.breachlock.com_Discovered host",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x5171",
							name: "Discovered host",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.57Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51cf",
						name: "app.breachlock.com_Web Application Firewall Present",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x5156",
							name: "Web Application Firewall Present",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.571Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51d0",
						name: "app.breachlock.com_Crawled url",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x5178",
							name: "Crawled url",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.573Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51d1",
						name: "app.breachlock.com_Web Application Does Not Supply a Permissions Policy",
						vulnerability: {
							cvssScore: 0,
							severity: "INFORMATIONAL",
							id: "0x5151",
							name: "Web Application Does Not Supply a Permissions Policy",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.574Z",
						findingType: "Rediscovered",
					},
					{
						id: "0x51d2",
						name: "app.breachlock.com_Web Application Does Not Supply a Content Security Policy",
						vulnerability: {
							cvssScore: 3.1,
							severity: "LOW",
							id: "0x517a",
							name: "Web Application Does Not Supply a Content Security Policy",
						},
						wfName: "ngsam-web-1-0-0-hhw1crpj",
						isAutoAdded: true,
						isFalsePositive: false,
						isManual: false,
						isPatched: false,
						updatedAt: "2024-01-29T07:31:32.566Z",
						findingType: "Rediscovered",
					},
				],
			},
		],
	},
};
