export const CommentBoxDataDummyData = {
	queryPentestComments: [
		{
			id: "0x32835f",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample Pentest Comment.",
			name: "Test Pentest Comment",
			attachments: [],
			createdAt: "2024-09-27T07:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x325bb4",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982a",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.1",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-27T07:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982b",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.2",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T07:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982c",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.3",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982d",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.4",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982e",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.5",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x33982f",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.6",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339830",
			email: "adilakshmi.b@brachlock.com",
			message: "Sample vuln Comment.7",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Adilakshmi Bonala",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339831",
			email: "sunil.k@brachlock.com",
			message: "Sample vuln Comment.7",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339832",
			email: "sunil.k@gmail.com",
			message: "Sample vuln Comment.7",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339833",
			email: "sunil.k@gmail.com",
			message: "Sample vuln Comment.8",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339834",
			email: "sunil.k@gmail.com",
			message:
				"Sample vuln Comment.8 test testt test tets tets testtttesttt. etsttttttetsttetstttest testt",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-28T08:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339835",
			email: "sunil.k@gmail.com",
			message:
				"Sample vuln Comment.8 test testt test tets tets testtttesttt. etsttttttetsttetstttest testt",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-29T09:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339836",
			email: "sunil.k@gmail.com",
			message:
				"Sample vuln Comment.8 test testt test tets tets testtttesttt. etsttttttetsttetstttest testt",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-29T10:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339837",
			email: "sunil.k@gmail.com",
			message:
				"Sample vuln Comment.8 test testt test tets tets testtttesttt. etsttttttetsttetstttest testt",
			name: "Test Vuln Comment",
			attachments: [],
			createdAt: "2024-09-29T10:33:59.678857Z",
			fullName: "Sunil Kumar",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
		{
			id: "0x339850",
			email: "",
			message: "another oneeeeee",
			name: "76e43a6e-0a6b-4223-942a-a4080f302aad",
			attachments: [""],
			createdAt: "2024-10-16T10:23:45Z",
			fullName: "",
			pentestId: "0x325b99",
			vulnerabilityId: "0x328481",
			isRead: false,
			isSeenByAdmin: false,
			isSeenByUser: false,
			isPublic: false,
			isArchived: false,
		},
	],
};
