/* eslint-disable quotes */
export const withoutPOC = [
	{
		hlfind: "Web Server has HSTS Disabled",
		findingdesc:
			"The web application was found to have HTTP Strict Transport Security (HSTS) disabled. HSTS is a web security policy mechanism designed to help safeguard against man-in-the-middle (MITM) attacks affecting protocol security such as protocol downgrade attacks, and cookie hijacking caused by transmission of cookies over unencrypted connections. HSTS restricts compliant client software (such as browsers) from interacting with the web application over non-HTTPS connections.\r\n\r\nHSTS can be enabled by adding a response header with the name Strict-Transport-Security and the value max-age=expireTime, where expireTime is the time in seconds that browsers should remember that the site should only be accessed using HTTPS. Including the includeSubDomains flag will propagate this to all subdomains.",
		cve: null,
		cwe_id: "CWE-319",
		cvss_vector: "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
		bid: "4.8",
		seealso:
			"A screenshot showing the absence of the Strict-Transport-Security HTTP response header in an application response.",
		solution:
			"Return an appropriate Strict-Transport-Security HTTP header in application responses.",
		reference:
			"https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security\nhttps://portswigger.net/kb/issues/01000300_strict-transport-security-not-enforced\nhttps://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security",
		scan_url: '["[\\"https://petstore.swagger.io/v2/pet\\"]"]',
		finding_standard_text: "A3: 2017 - Sensitive Data Exposure",
		finding_Standard: "OWASP",
		appliance_name: null,
		riskrating: "2",
		risk: "Medium",
		patchingStatus: "Patched",
		vid: 1471,
		id: 46634,
		access: 0,
		pcistatus: null,
		compliance_Standard: null,
		ticket_id: null,
		hostid: 35457,
		ticket_number: null,
		ticket_status: null,
		serviceid: null,
		resources: null,
		region: null,
		audit_status: 0,
		port: '{"443":"https"}',
		service: null,
		enc_id: "cd0e86c983ea7655ba69b2943cedf17643967b6d",
		user_id: 0,
		pentest: null,
		status: null,
		starttime: "01-04-2021",
		modified_date: "04-22-2021",
		findingReportHostId: 35457,
		report_id: 554,
		hlvid: 1387308,
		userPatchedFinding: "05-22-2021",
		rule_id: 1569,
		IsPatch: 1,
		patch_comment: "",
		findingReportPluginId: null,
		findingVidPluginId: 47,
		scanop: '["Here the host is vulnerable to Headers Strict-Transport-Security vulnerability."]',
		scan_status: 0,
		hostname: "https://petstore.swagger.io/v2/",
		public_name: "API Endpoints",
		ipaddress: "https://petstore.swagger.io/v2/",
		scanHostHostId: 35457,
		profile: 9,
		endpoint: null,
		endpointid: "[]",
		lastScan: "05-22-2021 11:15:21",
	},
];
